# Generated by Django 5.0.6 on 2024-06-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=1000)),
                ('pin_code', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/profile_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='TourPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='Images/Dam/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='Images/Dam/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='Images/Dam/')),
                ('video1_link', models.CharField(blank=True, max_length=1200, null=True)),
                ('video2_link', models.CharField(blank=True, max_length=1200, null=True)),
                ('video3_link', models.CharField(blank=True, max_length=1200, null=True)),
                ('video4_link', models.CharField(blank=True, max_length=1200, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('popular', models.BooleanField()),
                ('categoty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.category')),
            ],
        ),
    ]
